compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.4.cjs

plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"

packageExtensions:
  "@firebase/analytics-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/app-check-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/auth-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/functions-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/installations-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/messaging-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/performance-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/remote-config-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/storage-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@firebase/database-compat@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "firebase-admin@*":
    peerDependencies:
      "@firebase/app-types": "*"
  "@vue/babel-plugin-jsx@*":
    peerDependencies:
      "@babel/core": "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@babel/core": "*"
  "postcss-loader@*":
    dependencies:
      "autoprefixer": "*"
  "postcss@*":
    dependencies:
      "autoprefixer": "*"
