---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: avalon-tls
  namespace: default
spec:
  secretName: avalon-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'avalon.onl'
  dnsNames:
    - avalon.fu.io
    - avalon.shamm.as
    - www.avalon.onl
    - avalon.onl
